---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: INFO
- type: document
  path: data/theme.json
  label: 'О сайте '
- type: document
  path: data/contacts.json
  label: Контакты
- type: heading
  label: КОНТЕНТ
- type: directory
  path: products
  label: Продукты
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - product
- type: directory
  path: categories
  label: Категории
  create: documents
  match: "**/*.md"
  templates:
  - category
- type: directory
  path: pages
  label: Страницы
  create: all
  match: "**/*.md"
  templates:
  - page
- type: directory
  path: blocks
  label: Блоки страниц
  create: all
  match: "**/*.md"
  templates:
  - project
  - page-block
upload_dir: uploads
public_path: https://res.cloudinary.com/da4me/fl_progressive,q_auto:best
front_matter_path: https://res.cloudinary.com/da4me
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  publish_command: gridsome build
  output_directory: dist
  preview_command: gridsome build
